<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>be7dc312-c1a7-451a-9d7f-07dc13d94ada</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiasoftNanus.PhoneBook.Application\MiasoftNanus.PhoneBook.Application.csproj" />
    <ProjectReference Include="..\MiasoftNanus.PhoneBook.Contracts\MiasoftNanus.PhoneBook.Contracts.csproj" />
    <ProjectReference Include="..\MiasoftNanus.PhoneBook.Domain\MiasoftNanus.PhoneBook.Domain.csproj" />
    <ProjectReference Include="..\MiasoftNanus.PhoneBook.Infrastructure\MiasoftNanus.PhoneBook.Infrastructure.csproj" />
  </ItemGroup>

</Project>
